### ISSUE TITLE
npm run dev报错了，新手看不出webpack还是哪里的问题？但是build是ok的~

### ISSUE THREAD

**Issue by lgs3137** [jiangqizheng/vue2-MiniQQ#7]
> vue-miniqq@1.0.0 dev D:\nodejs\test\vue2-MiniQQ
> node build/dev-server.js

events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8888
    at Object.exports._errnoException (util.js:1029:11)
    at exports._exceptionWithHostPort (util.js:1052:20)
    at Server._listen2 (net.js:1264:14)
    at listen (net.js:1300:10)
    at Server.listen (net.js:1378:9)
    at Function.listen (D:\nodejs\test\vue2-MiniQQ\node_modules\.4.15.2@express\lib\application.js:618:24)
    at Object.<anonymous> (D:\nodejs\test\vue2-MiniQQ\build\dev-server.js:117:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:425:7)
    at startup (bootstrap_node.js:146:9)
    at bootstrap_node.js:540:3

**Comment by jiangqizheng** [comment]
端口被占用,打开config/index 文件把端口改一下就好
